### ISSUE TITLE
TLSR8250 - OTA: possible to get bytes read/total firmware size?

### ISSUE THREAD

**Issue by danergo** [pvvx/BZdevice#7]
Title says (almost) all.

Is there any API you know to get the:

- total size of the firmware
- bytes received

This way we could calculate the load percentage, and display on screen during fw update.

I couldn't find any reasonable resources, so this might be impossible due to lack of API. It would be great if you could confirm this is either possible or not.

**Comment by pvvx** [comment]
> Is there any API you know to get the:

The size is in the OTA file header (firmware).
BLE OTA is downloaded in blocks of 16 bytes per transmission.

What other API?

**Comment by danergo** [comment]
On my SDK, I only have these:

```
extern int otaRead(void* p);
extern int otaWrite(void* p);
```

And I registered a prewrite function which sets `blt_ota_start_tick = clock_time() | 1`.

> BLE OTA is downloaded in blocks of 16 bytes per transmission.

So above `void* p` chunks otaRead and otaWrite functions are all 16bytes?

**Comment by pvvx** [comment]
Described in the SDK manual on the [Telink website](https://wiki.telink-semi.cn/wiki/chip-series/TLSR825x-Series/).
