### ISSUE TITLE
TLSR8250 - Sleep ruins display

### ISSUE THREAD

**Issue by danergo** [pvvx/BZdevice#8]
I'm almost finished with everything for the LYWSD02MMC.

In case I have this below line in my main:

```
bls_pm_setSuspendMask(SUSPEND_DISABLE);
```

Screen works, updates, behaves correctly.

But, if I replace this with 

```
bls_pm_setSuspendMask(SUSPEND_ADV | DEEPSLEEP_RETENTION_ADV | SUSPEND_CONN | DEEPSLEEP_RETENTION_CONN);
```

Screen starts behaving wrong: for example if I display 3 then 4, it will display 9.

I think the Busy_N pin is not working the same as with other displays, so I applied a simplier logic:

```
if (epd_stage != IDLE) sleep_disable
else SUSPEND_ADV | DEEPSLEEP_RETENTION_ADV | SUSPEND_CONN | DEEPSLEEP_RETENTION_CONN
```

Without thinking too much, do you have any idea what can cause this? (buffer is in RAM).

**Comment by pvvx** [comment]
I won't comment on anything without full open source code. There could be hundreds of reasons why "sleep modes" don't work...
